# Cloud Build configuration for Cloud Shell custom image
#
# Prerequisites:
#   1. Create Artifact Registry repository (already done)
#   2. Store API keys in Secret Manager:
#      echo -n "sk-ant-..." | gcloud secrets create anthropic-api-key --data-file=-
#      echo -n "sk-..." | gcloud secrets create openai-api-key --data-file=-
#
# Usage:
#   gcloud builds submit --config=cloudbuild.yaml \
#     --substitutions=_ANTHROPIC_API_KEY=sk-ant-xxx,_OPENAI_API_KEY=sk-xxx .
#
# Or use Secret Manager (recommended):
#   gcloud builds submit --config=cloudbuild.yaml .

substitutions:
  _REGION: europe-west4
  _REPOSITORY: cloudshell-images
  _IMAGE_NAME: cloudshell-ai-team
  _TAG: latest
  _ANTHROPIC_API_KEY: ""  # Pass via --substitutions or use availableSecrets
  _OPENAI_API_KEY: ""     # Pass via --substitutions or use availableSecrets

# Uncomment to use Secret Manager instead of substitutions:
# availableSecrets:
#   secretManager:
#     - versionName: projects/${PROJECT_ID}/secrets/anthropic-api-key/versions/latest
#       env: 'ANTHROPIC_API_KEY'
#     - versionName: projects/${PROJECT_ID}/secrets/openai-api-key/versions/latest
#       env: 'OPENAI_API_KEY'

steps:
  # Build the Docker image with API keys as build args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY}'
      - '--build-arg'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG}'
      - '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG}'

# Images to store in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${_TAG}'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'

tags:
  - 'cloudshell'
  - 'ai-tools'
