#!/bin/bash
# setup-keys.sh - Interactive API key setup for Cloud Shell AI tools
# Run this once to configure all AI tools with persistent authentication

set -e

KEYS_FILE="$HOME/.ai-keys"
CLAUDE_CONFIG_DIR="$HOME/.claude"
CODEX_CONFIG_DIR="$HOME/.codex"
GEMINI_CONFIG_DIR="$HOME/.gemini"

echo "========================================"
echo "  Cloud Shell AI Tools - API Key Setup"
echo "========================================"
echo ""
echo "This script will configure persistent authentication for:"
echo "  - Claude Code (Anthropic)"
echo "  - Codex (OpenAI)"
echo "  - Gemini CLI (Google)"
echo ""

# Function to read API key securely
read_key() {
    local prompt="$1"
    local key=""
    read -sp "$prompt: " key
    echo ""
    echo "$key"
}

# Function to check if key is valid format (basic validation)
validate_key() {
    local key="$1"
    local type="$2"

    case "$type" in
        anthropic)
            [[ "$key" =~ ^sk-ant- ]] && return 0
            ;;
        openai)
            [[ "$key" =~ ^sk- ]] && return 0
            ;;
        google)
            [[ "$key" =~ ^AIza ]] && return 0
            ;;
    esac
    return 1
}

# Create config directories
mkdir -p "$CLAUDE_CONFIG_DIR" "$CODEX_CONFIG_DIR" "$GEMINI_CONFIG_DIR"

# --- Anthropic/Claude Setup ---
echo ""
echo "--- Claude Code (Anthropic) ---"
echo "Get your API key from: https://console.anthropic.com/settings/keys"
ANTHROPIC_KEY=$(read_key "Enter Anthropic API key (sk-ant-...)")

if [ -n "$ANTHROPIC_KEY" ]; then
    if validate_key "$ANTHROPIC_KEY" "anthropic"; then
        # Create apiKeyHelper script for Claude Code
        cat > "$CLAUDE_CONFIG_DIR/get-api-key.sh" << 'SCRIPT'
#!/bin/bash
source "$HOME/.ai-keys" 2>/dev/null
echo "$ANTHROPIC_API_KEY"
SCRIPT
        chmod +x "$CLAUDE_CONFIG_DIR/get-api-key.sh"

        # Configure Claude to use the helper
        claude config set --global apiKeyHelper "$CLAUDE_CONFIG_DIR/get-api-key.sh" 2>/dev/null || true

        echo "  [OK] Claude Code configured"
    else
        echo "  [WARN] Key doesn't match expected format (sk-ant-...), saving anyway"
    fi
else
    echo "  [SKIP] No Anthropic key provided"
fi

# --- OpenAI/Codex Setup ---
echo ""
echo "--- Codex (OpenAI) ---"
echo "Get your API key from: https://platform.openai.com/api-keys"
OPENAI_KEY=$(read_key "Enter OpenAI API key (sk-...)")

if [ -n "$OPENAI_KEY" ]; then
    if validate_key "$OPENAI_KEY" "openai"; then
        # Login to Codex with the API key
        echo "$OPENAI_KEY" | codex login --with-api-key 2>/dev/null || {
            # Fallback: store in config
            echo "  [INFO] Storing key for manual login"
        }
        echo "  [OK] Codex configured"
    else
        echo "  [WARN] Key doesn't match expected format (sk-...), saving anyway"
    fi
else
    echo "  [SKIP] No OpenAI key provided"
fi

# --- Google/Gemini Setup ---
echo ""
echo "--- Gemini CLI (Google) ---"
echo "Get your API key from: https://aistudio.google.com/apikey"
GEMINI_KEY=$(read_key "Enter Gemini API key (AIza...)")

if [ -n "$GEMINI_KEY" ]; then
    if validate_key "$GEMINI_KEY" "google"; then
        echo "  [OK] Gemini key saved"
    else
        echo "  [WARN] Key doesn't match expected format (AIza...), saving anyway"
    fi
else
    echo "  [SKIP] No Gemini key provided"
fi

# --- Save keys to persistent file ---
echo ""
echo "--- Saving keys ---"

cat > "$KEYS_FILE" << EOF
# AI API Keys - Generated by setup-keys.sh
# This file is sourced by ~/.bashrc for persistent authentication

export ANTHROPIC_API_KEY="$ANTHROPIC_KEY"
export OPENAI_API_KEY="$OPENAI_KEY"
export GEMINI_API_KEY="$GEMINI_KEY"
EOF

chmod 600 "$KEYS_FILE"

# Add source to bashrc if not already present
if ! grep -q "source.*\.ai-keys" "$HOME/.bashrc" 2>/dev/null; then
    echo "" >> "$HOME/.bashrc"
    echo "# Load AI API keys" >> "$HOME/.bashrc"
    echo '[ -f "$HOME/.ai-keys" ] && source "$HOME/.ai-keys"' >> "$HOME/.bashrc"
fi

# Source the keys now
source "$KEYS_FILE"

echo ""
echo "========================================"
echo "  Setup Complete!"
echo "========================================"
echo ""
echo "Your API keys are stored in: $KEYS_FILE"
echo "Keys will be automatically loaded in new terminal sessions."
echo ""
echo "To use the tools now, run:"
echo "  source ~/.ai-keys"
echo ""
echo "Then start any tool:"
echo "  claude    # Claude Code"
echo "  codex     # OpenAI Codex"
echo "  gemini    # Google Gemini"
echo ""
